.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH VBOXVIDEO 4 2017-10-14 __vendorversion__
.SH NAME
vboxvideo \- VirtualBox video driver
.SH SYNOPSIS
.nf
.B "Section \*qDevice\*q"
.BI "  Identifier \*q"  devname \*q
.B  "  Driver \*qvboxvideo\*q"
\ \ ...
.B EndSection
.fi
.SH DESCRIPTION
.B vboxvideo
is an
.B Xorg
driver for the VirtualBox virtual video card.
.SH SUPPORTED HARDWARE
The
.B vboxvideo
driver supports the VirtualBox virtual video card.
.SH CONFIGURATION DETAILS
Please refer to
.BR xorg.conf (5)
for general configuration details.
.SH "SEE ALSO"
.BR Xorg (1),
.BR Xserver (1),
.BR xorg.conf (5),
.BR X (7)
.SH AUTHORS
Authors include: Paulo Ce\'sar Pereira de Andrade, Michael Thayer.
